name: 'update docs'

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: 'deploy github pages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build && npm run build-spec

      - name: Deploy docs
        run: ./scripts/auto-deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
